spring:
  datasource: # 띄어쓰기 2개
    url: jdbc:h2:tcp://localhost/~/minishop # 띄어쓰기 4개
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: # 띄어쓰기 2개
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시점에 테이블을 drop하고 다시 생성한다
    properties:
      hibernate:
        format_sql: true

logging.level: # 띄어쓰기 없음
  org.hibernate.SQL: debug # 로거를 통해 하이버네이트 실행 SQL을 남긴다
  # org.hibernate.type: trace
